// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://afutvxbklbcxjpgrzoor.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "sb_publishable_14Lkn6VpWxT0L8x54R1lvA_AB3Bg-Q2";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);